<?php

use Illuminate\Database\Seeder;
use App\FilterPropertyType;

class FilterPropertyTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            // ///1            
            // ['filter_id' => 1  , 'property_type_id' => 1 ],
            // ['filter_id' => 2  , 'property_type_id' => 1 ],
            // ['filter_id' => 3  , 'property_type_id' => 1 ],
            // ['filter_id' => 4  , 'property_type_id' => 1 ],
            // ['filter_id' => 5  , 'property_type_id' => 1 ],
            // ['filter_id' => 6  , 'property_type_id' => 1 ],

            // ['filter_id' => 7  , 'property_type_id' => 1 ],
            // ['filter_id' => 8  , 'property_type_id' => 1 ],
            // ['filter_id' => 9  , 'property_type_id' => 1 ],
            // ['filter_id' => 12 , 'property_type_id' => 1 ],
            // ['filter_id' => 13 , 'property_type_id' => 1 ],
            // ['filter_id' => 14 , 'property_type_id' => 1 ],
            // ['filter_id' => 15 , 'property_type_id' => 1 ],
            // ['filter_id' => 16 , 'property_type_id' => 1 ],

            // ['filter_id' => 17 , 'property_type_id' => 1 ],
            // ['filter_id' => 18 , 'property_type_id' => 1 ],
            // ['filter_id' => 19 , 'property_type_id' => 1 ],
            // ['filter_id' => 20 , 'property_type_id' => 1 ],
            // ['filter_id' => 21 , 'property_type_id' => 1 ],
            // ['filter_id' => 22 , 'property_type_id' => 1 ],
            // ['filter_id' => 23 , 'property_type_id' => 1 ],
            // ['filter_id' => 24 , 'property_type_id' => 1 ],
            // ['filter_id' => 27 , 'property_type_id' => 1 ],
            // ['filter_id' => 29 , 'property_type_id' => 1 ],
            // ['filter_id' => 30 , 'property_type_id' => 1 ],
            // ['filter_id' => 31 , 'property_type_id' => 1 ],
            // ['filter_id' => 32 , 'property_type_id' => 1 ],
            // ['filter_id' => 33 , 'property_type_id' => 1 ],
            // ['filter_id' => 34 , 'property_type_id' => 1 ],
            // ['filter_id' => 35 , 'property_type_id' => 1 ],
            // ['filter_id' => 36 , 'property_type_id' => 1 ],
            // ['filter_id' => 37 , 'property_type_id' => 1 ],
            // ['filter_id' => 38 , 'property_type_id' => 1 ],

            // ['filter_id' => 39 , 'property_type_id' => 1 ],
            // ['filter_id' => 40 , 'property_type_id' => 1 ],
            // ['filter_id' => 41 , 'property_type_id' => 1 ],
            // ['filter_id' => 42 , 'property_type_id' => 1 ],
            // ['filter_id' => 43 , 'property_type_id' => 1 ],
            // ['filter_id' => 44 , 'property_type_id' => 1 ],
            // ['filter_id' => 45 , 'property_type_id' => 1 ],

            // ['filter_id' => 46 , 'property_type_id' => 1 ],
            // ['filter_id' => 47 , 'property_type_id' => 1 ],
            // ['filter_id' => 48 , 'property_type_id' => 1 ],
            // ['filter_id' => 49 , 'property_type_id' => 1 ],

            // ['filter_id' => 50 , 'property_type_id' => 1 ],
            // ['filter_id' => 51 , 'property_type_id' => 1 ],
            // ['filter_id' => 52 , 'property_type_id' => 1 ],
            // ['filter_id' => 53 , 'property_type_id' => 1 ],
            // ['filter_id' => 54 , 'property_type_id' => 1 ],
            // ['filter_id' => 55 , 'property_type_id' => 1 ],
            // ['filter_id' => 56 , 'property_type_id' => 1 ],
            // ['filter_id' => 57 , 'property_type_id' => 1 ],
            // ['filter_id' => 58 , 'property_type_id' => 1 ],

            // ['filter_id' => 59 , 'property_type_id' => 1 ],
            // ['filter_id' => 60 , 'property_type_id' => 1 ],
            // ['filter_id' => 61 , 'property_type_id' => 1 ],
            // ['filter_id' => 62 , 'property_type_id' => 1 ],
            // ['filter_id' => 63 , 'property_type_id' => 1 ],
            // ['filter_id' => 64 , 'property_type_id' => 1 ],
            // ['filter_id' => 65 , 'property_type_id' => 1 ],
            // ['filter_id' => 66 , 'property_type_id' => 1 ],
            // ['filter_id' => 67 , 'property_type_id' => 1 ],
            // ['filter_id' => 69 , 'property_type_id' => 1 ],

            // ['filter_id' => 70 , 'property_type_id' => 1 ],
            // ['filter_id' => 71 , 'property_type_id' => 1 ],
            // ['filter_id' => 72 , 'property_type_id' => 1 ],
            // ['filter_id' => 73 , 'property_type_id' => 1 ],
            // ['filter_id' => 74 , 'property_type_id' => 1 ],
            // ['filter_id' => 75 , 'property_type_id' => 1 ],
            // ['filter_id' => 76 , 'property_type_id' => 1 ],
            // ['filter_id' => 77 , 'property_type_id' => 1 ],
            // ['filter_id' => 80 , 'property_type_id' => 1 ],
            // ['filter_id' => 82 , 'property_type_id' => 1 ],
            // ['filter_id' => 83 , 'property_type_id' => 1 ],
            // ['filter_id' => 84 , 'property_type_id' => 1 ],
            // ['filter_id' => 85 , 'property_type_id' => 1 ],
            // ['filter_id' => 86 , 'property_type_id' => 1 ],
            // ['filter_id' => 87 , 'property_type_id' => 1 ],
            // ['filter_id' => 88 , 'property_type_id' => 1 ],
            // ['filter_id' => 89 , 'property_type_id' => 1 ],
            // ['filter_id' => 90 , 'property_type_id' => 1 ],
            // ['filter_id' => 91 , 'property_type_id' => 1 ],
            // ['filter_id' => 92 , 'property_type_id' => 1 ],

            // ['filter_id' => 93 , 'property_type_id' => 1 ],
            // ['filter_id' => 94 , 'property_type_id' => 1 ],
            // ['filter_id' => 95 , 'property_type_id' => 1 ],
            // ['filter_id' => 96 , 'property_type_id' => 1 ],
            // ['filter_id' => 97 , 'property_type_id' => 1 ],
            // ['filter_id' => 98 , 'property_type_id' => 1 ],
            // ['filter_id' => 99 , 'property_type_id' => 1 ],

            // ['filter_id' => 100 , 'property_type_id' => 1 ],
            // ['filter_id' => 101 , 'property_type_id' => 1 ],
            // ['filter_id' => 102 , 'property_type_id' => 1 ],
            // ['filter_id' => 103 , 'property_type_id' => 1 ],

            // ['filter_id' => 104 , 'property_type_id' => 1 ],
            // ['filter_id' => 105 , 'property_type_id' => 1 ],
            // ['filter_id' => 106 , 'property_type_id' => 1 ],
            // ['filter_id' => 107 , 'property_type_id' => 1 ],
            // ['filter_id' => 108 , 'property_type_id' => 1 ],
            // ['filter_id' => 109 , 'property_type_id' => 1 ],
            // ['filter_id' => 110 , 'property_type_id' => 1 ],
            // ['filter_id' => 111 , 'property_type_id' => 1 ],
            // ['filter_id' => 112 , 'property_type_id' => 1 ],

            // ['filter_id' => 113 , 'property_type_id' => 1 ],
            // ['filter_id' => 114 , 'property_type_id' => 1 ],
            // ['filter_id' => 115 , 'property_type_id' => 1 ],
            // ['filter_id' => 116 , 'property_type_id' => 1 ],
            // ['filter_id' => 117 , 'property_type_id' => 1 ],
            // ['filter_id' => 118 , 'property_type_id' => 1 ],
            // ['filter_id' => 119 , 'property_type_id' => 1 ],
            // ['filter_id' => 120 , 'property_type_id' => 1 ],
            // ['filter_id' => 121 , 'property_type_id' => 1 ],
            // ['filter_id' => 123 , 'property_type_id' => 1 ],

            // ['filter_id' => 124 , 'property_type_id' => 1 ],
            // ['filter_id' => 125 , 'property_type_id' => 1 ],
            // ['filter_id' => 126 , 'property_type_id' => 1 ],
            // ['filter_id' => 127 , 'property_type_id' => 1 ],
            // ['filter_id' => 128 , 'property_type_id' => 1 ],
            // ['filter_id' => 129 , 'property_type_id' => 1 ],
            // ['filter_id' => 130 , 'property_type_id' => 1 ],
            // ['filter_id' => 131 , 'property_type_id' => 1 ],
            // ['filter_id' => 132 , 'property_type_id' => 1 ],
            // ['filter_id' => 133 , 'property_type_id' => 1 ],
            // ['filter_id' => 134 , 'property_type_id' => 1 ],
            // ['filter_id' => 135 , 'property_type_id' => 1 ],
            // ['filter_id' => 136 , 'property_type_id' => 1 ],
            // ['filter_id' => 137 , 'property_type_id' => 1 ],
            // ['filter_id' => 138 , 'property_type_id' => 1 ],
            // ['filter_id' => 139 , 'property_type_id' => 1 ],
            // ['filter_id' => 140 , 'property_type_id' => 1 ],
            // ['filter_id' => 141 , 'property_type_id' => 1 ],
            // ['filter_id' => 144 , 'property_type_id' => 1 ],
            // ['filter_id' => 145 , 'property_type_id' => 1 ],
            // ['filter_id' => 146 , 'property_type_id' => 1 ],
            // ['filter_id' => 147 , 'property_type_id' => 1 ],
            // ['filter_id' => 148 , 'property_type_id' => 1 ],
            // ['filter_id' => 149 , 'property_type_id' => 1 ],

            // ['filter_id' => 150 , 'property_type_id' => 1 ],
            // ['filter_id' => 151 , 'property_type_id' => 1 ],
            // ['filter_id' => 152 , 'property_type_id' => 1 ],
            // ['filter_id' => 153 , 'property_type_id' => 1 ],
            // ['filter_id' => 154 , 'property_type_id' => 1 ],
            // ['filter_id' => 156 , 'property_type_id' => 1 ],

            // ///2
            // ['filter_id' => 1  , 'property_type_id' => 2 ],
            // ['filter_id' => 2  , 'property_type_id' => 2 ],
            // ['filter_id' => 3  , 'property_type_id' => 2 ],
            // ['filter_id' => 5  , 'property_type_id' => 2 ],
            // ['filter_id' => 6  , 'property_type_id' => 2 ],

            // ['filter_id' => 7  , 'property_type_id' => 2 ],
            // ['filter_id' => 8  , 'property_type_id' => 2 ],
            // ['filter_id' => 9  , 'property_type_id' => 2 ],
            // ['filter_id' => 12 , 'property_type_id' => 2 ],
            // ['filter_id' => 13 , 'property_type_id' => 2 ],
            // ['filter_id' => 14 , 'property_type_id' => 2 ],
            // ['filter_id' => 15 , 'property_type_id' => 2 ],
            // ['filter_id' => 16 , 'property_type_id' => 2 ],

            // ['filter_id' => 17 , 'property_type_id' => 2 ],
            // ['filter_id' => 18 , 'property_type_id' => 2 ],
            // ['filter_id' => 19 , 'property_type_id' => 2 ],
            // ['filter_id' => 20 , 'property_type_id' => 2 ],
            // ['filter_id' => 21 , 'property_type_id' => 2 ],
            // ['filter_id' => 22 , 'property_type_id' => 2 ],
            // ['filter_id' => 23 , 'property_type_id' => 2 ],
            // ['filter_id' => 24 , 'property_type_id' => 2 ],
            // ['filter_id' => 25 , 'property_type_id' => 2 ],
            // ['filter_id' => 26 , 'property_type_id' => 2 ],
            // // ['filter_id' => 27 , 'property_type_id' => 2 ],
            // ['filter_id' => 28 , 'property_type_id' => 2 ],
            // ['filter_id' => 29 , 'property_type_id' => 2 ],
            // ['filter_id' => 31 , 'property_type_id' => 2 ],
            // ['filter_id' => 32 , 'property_type_id' => 2 ],
            // ['filter_id' => 33 , 'property_type_id' => 2 ],
            // ['filter_id' => 34 , 'property_type_id' => 2 ],
            // ['filter_id' => 35 , 'property_type_id' => 2 ],
            // ['filter_id' => 36 , 'property_type_id' => 2 ],
            // ['filter_id' => 37 , 'property_type_id' => 2 ],
            // ['filter_id' => 38 , 'property_type_id' => 2 ],

            // ['filter_id' => 39 , 'property_type_id' => 2 ],
            // ['filter_id' => 40 , 'property_type_id' => 2 ],
            // ['filter_id' => 41 , 'property_type_id' => 2 ],
            // ['filter_id' => 42 , 'property_type_id' => 2 ],
            // ['filter_id' => 43 , 'property_type_id' => 2 ],
            // ['filter_id' => 44 , 'property_type_id' => 2 ],
            // ['filter_id' => 45 , 'property_type_id' => 2 ],

            // ['filter_id' => 46 , 'property_type_id' => 2 ],
            // ['filter_id' => 47 , 'property_type_id' => 2 ],
            // ['filter_id' => 48 , 'property_type_id' => 2 ],
            // ['filter_id' => 49 , 'property_type_id' => 2 ],

            // ['filter_id' => 50 , 'property_type_id' => 2 ],
            // ['filter_id' => 51 , 'property_type_id' => 2 ],
            // ['filter_id' => 52 , 'property_type_id' => 2 ],
            // ['filter_id' => 53 , 'property_type_id' => 2 ],
            // ['filter_id' => 54 , 'property_type_id' => 2 ],
            // ['filter_id' => 55 , 'property_type_id' => 2 ],
            // ['filter_id' => 56 , 'property_type_id' => 2 ],
            // ['filter_id' => 57 , 'property_type_id' => 2 ],
            // ['filter_id' => 58 , 'property_type_id' => 2 ],

            // ['filter_id' => 59 , 'property_type_id' => 2 ],
            // ['filter_id' => 60 , 'property_type_id' => 2 ],
            // ['filter_id' => 61 , 'property_type_id' => 2 ],
            // ['filter_id' => 62 , 'property_type_id' => 2 ],
            // ['filter_id' => 63 , 'property_type_id' => 2 ],
            // ['filter_id' => 64 , 'property_type_id' => 2 ],
            // ['filter_id' => 65 , 'property_type_id' => 2 ],
            // ['filter_id' => 66 , 'property_type_id' => 2 ],
            // ['filter_id' => 67 , 'property_type_id' => 2 ],
            // ['filter_id' => 68 , 'property_type_id' => 2 ],
            // ['filter_id' => 69 , 'property_type_id' => 2 ],

            // ['filter_id' => 70 , 'property_type_id' => 2 ],
            // ['filter_id' => 71 , 'property_type_id' => 2 ],
            // ['filter_id' => 72 , 'property_type_id' => 2 ],
            // ['filter_id' => 73 , 'property_type_id' => 2 ],
            // ['filter_id' => 74 , 'property_type_id' => 2 ],
            // ['filter_id' => 75 , 'property_type_id' => 2 ],
            // ['filter_id' => 76 , 'property_type_id' => 2 ],
            // ['filter_id' => 77 , 'property_type_id' => 2 ],
            // ['filter_id' => 78 , 'property_type_id' => 2 ],
            // ['filter_id' => 79 , 'property_type_id' => 2 ],
            // // ['filter_id' => 80 , 'property_type_id' => 2 ],
            // ['filter_id' => 81 , 'property_type_id' => 2 ],
            // ['filter_id' => 82 , 'property_type_id' => 2 ],
            // ['filter_id' => 84 , 'property_type_id' => 2 ],
            // ['filter_id' => 85 , 'property_type_id' => 2 ],
            // ['filter_id' => 86 , 'property_type_id' => 2 ],
            // ['filter_id' => 87 , 'property_type_id' => 2 ],
            // ['filter_id' => 88 , 'property_type_id' => 2 ],
            // ['filter_id' => 89 , 'property_type_id' => 2 ],
            // ['filter_id' => 90 , 'property_type_id' => 2 ],
            // ['filter_id' => 91 , 'property_type_id' => 2 ],
            // ['filter_id' => 92 , 'property_type_id' => 2 ],

            // ['filter_id' => 93 , 'property_type_id' => 2 ],
            // ['filter_id' => 94 , 'property_type_id' => 2 ],
            // ['filter_id' => 95 , 'property_type_id' => 2 ],
            // ['filter_id' => 96 , 'property_type_id' => 2 ],
            // ['filter_id' => 97 , 'property_type_id' => 2 ],
            // ['filter_id' => 98 , 'property_type_id' => 2 ],
            // ['filter_id' => 99 , 'property_type_id' => 2 ],

            // ['filter_id' => 100 , 'property_type_id' => 2 ],
            // ['filter_id' => 101 , 'property_type_id' => 2 ],
            // ['filter_id' => 102 , 'property_type_id' => 2 ],
            // ['filter_id' => 103 , 'property_type_id' => 2 ],

            // ['filter_id' => 104 , 'property_type_id' => 2 ],
            // ['filter_id' => 105 , 'property_type_id' => 2 ],
            // ['filter_id' => 106 , 'property_type_id' => 2 ],
            // ['filter_id' => 107 , 'property_type_id' => 2 ],
            // ['filter_id' => 108 , 'property_type_id' => 2 ],
            // ['filter_id' => 109 , 'property_type_id' => 2 ],
            // ['filter_id' => 110 , 'property_type_id' => 2 ],
            // ['filter_id' => 111 , 'property_type_id' => 2 ],
            // ['filter_id' => 112 , 'property_type_id' => 2 ],

            // ['filter_id' => 113 , 'property_type_id' => 2 ],
            // ['filter_id' => 114 , 'property_type_id' => 2 ],
            // ['filter_id' => 115 , 'property_type_id' => 2 ],
            // ['filter_id' => 116 , 'property_type_id' => 2 ],
            // ['filter_id' => 117 , 'property_type_id' => 2 ],
            // ['filter_id' => 118 , 'property_type_id' => 2 ],
            // ['filter_id' => 119 , 'property_type_id' => 2 ],
            // ['filter_id' => 120 , 'property_type_id' => 2 ],
            // ['filter_id' => 121 , 'property_type_id' => 2 ],
            // ['filter_id' => 122 , 'property_type_id' => 2 ],
            // ['filter_id' => 123 , 'property_type_id' => 2 ],

            // ['filter_id' => 124 , 'property_type_id' => 2 ],
            // ['filter_id' => 125 , 'property_type_id' => 2 ],
            // ['filter_id' => 126 , 'property_type_id' => 2 ],
            // ['filter_id' => 127 , 'property_type_id' => 2 ],
            // ['filter_id' => 128 , 'property_type_id' => 2 ],
            // ['filter_id' => 129 , 'property_type_id' => 2 ],
            // ['filter_id' => 130 , 'property_type_id' => 2 ],
            // ['filter_id' => 131 , 'property_type_id' => 2 ],
            // ['filter_id' => 132 , 'property_type_id' => 2 ],
            // ['filter_id' => 133 , 'property_type_id' => 2 ],
            // ['filter_id' => 134 , 'property_type_id' => 2 ],
            // ['filter_id' => 135 , 'property_type_id' => 2 ],
            // ['filter_id' => 136 , 'property_type_id' => 2 ],
            // ['filter_id' => 137 , 'property_type_id' => 2 ],
            // ['filter_id' => 138 , 'property_type_id' => 2 ],
            // ['filter_id' => 139 , 'property_type_id' => 2 ],
            // ['filter_id' => 140 , 'property_type_id' => 2 ],
            // ['filter_id' => 141 , 'property_type_id' => 2 ],
            // ['filter_id' => 142 , 'property_type_id' => 2 ],
            // ['filter_id' => 143 , 'property_type_id' => 2 ],
            // ['filter_id' => 144 , 'property_type_id' => 2 ],
            // ['filter_id' => 145 , 'property_type_id' => 2 ],
            // ['filter_id' => 146 , 'property_type_id' => 2 ],
            // ['filter_id' => 147 , 'property_type_id' => 2 ],
            // ['filter_id' => 148 , 'property_type_id' => 2 ],
            // ['filter_id' => 149 , 'property_type_id' => 2 ],

            // ['filter_id' => 150 , 'property_type_id' => 2 ],
            // ['filter_id' => 151 , 'property_type_id' => 2 ],
            // ['filter_id' => 152 , 'property_type_id' => 2 ],
            // ['filter_id' => 153 , 'property_type_id' => 2 ],
            // ['filter_id' => 154 , 'property_type_id' => 2 ],
            // ['filter_id' => 155 , 'property_type_id' => 2 ],
            // ['filter_id' => 156 , 'property_type_id' => 2 ],


            // ///3
            // ['filter_id' => 2  , 'property_type_id' => 3 ],

            // ['filter_id' => 7  , 'property_type_id' => 3 ],
            // ['filter_id' => 8  , 'property_type_id' => 3 ],
            // ['filter_id' => 9  , 'property_type_id' => 3 ],
            // ['filter_id' => 10 , 'property_type_id' => 3 ],
            // ['filter_id' => 11 , 'property_type_id' => 3 ],
            // ['filter_id' => 12 , 'property_type_id' => 3 ],
            // ['filter_id' => 13 , 'property_type_id' => 3 ],

            // ['filter_id' => 20 , 'property_type_id' => 3 ],
            // ['filter_id' => 33 , 'property_type_id' => 3 ],


            // ['filter_id' => 50 , 'property_type_id' => 3 ],
            // ['filter_id' => 52 , 'property_type_id' => 3 ],
            // ['filter_id' => 53 , 'property_type_id' => 3 ],
            // ['filter_id' => 54 , 'property_type_id' => 3 ],
            // ['filter_id' => 55 , 'property_type_id' => 3 ],
            // ['filter_id' => 56 , 'property_type_id' => 3 ],
            // ['filter_id' => 57 , 'property_type_id' => 3 ],
            // ['filter_id' => 58 , 'property_type_id' => 3 ],

            // ['filter_id' => 66 , 'property_type_id' => 3 ],

            // ['filter_id' => 73 , 'property_type_id' => 3 ],
            // ['filter_id' => 86 , 'property_type_id' => 3 ],



            // ['filter_id' => 104 , 'property_type_id' => 3 ],
            // ['filter_id' => 106 , 'property_type_id' => 3 ],
            // ['filter_id' => 107 , 'property_type_id' => 3 ],
            // ['filter_id' => 108 , 'property_type_id' => 3 ],
            // ['filter_id' => 109 , 'property_type_id' => 3 ],
            // ['filter_id' => 110 , 'property_type_id' => 3 ],
            // ['filter_id' => 111 , 'property_type_id' => 3 ],
            // ['filter_id' => 112 , 'property_type_id' => 3 ],

           
            // ['filter_id' => 120 , 'property_type_id' => 3 ],
          

       
         

            // ///4
            // ['filter_id' => 1  , 'property_type_id' => 4 ],
            // ['filter_id' => 2  , 'property_type_id' => 4 ],
            // ['filter_id' => 3  , 'property_type_id' => 4 ],
            // ['filter_id' => 4  , 'property_type_id' => 4 ],
            // ['filter_id' => 5  , 'property_type_id' => 4 ],
            // ['filter_id' => 6  , 'property_type_id' => 4 ],

            // ['filter_id' => 7  , 'property_type_id' => 4 ],
            // ['filter_id' => 8  , 'property_type_id' => 4 ],
            // ['filter_id' => 9  , 'property_type_id' => 4 ],
            // ['filter_id' => 12 , 'property_type_id' => 4 ],
            // ['filter_id' => 13 , 'property_type_id' => 4 ],
            // ['filter_id' => 14 , 'property_type_id' => 4 ],
            // ['filter_id' => 15 , 'property_type_id' => 4 ],
            // ['filter_id' => 16 , 'property_type_id' => 4 ],

            // ['filter_id' => 20 , 'property_type_id' => 4 ],
            // ['filter_id' => 21 , 'property_type_id' => 4 ],
            // ['filter_id' => 22 , 'property_type_id' => 4 ],
            // ['filter_id' => 23 , 'property_type_id' => 4 ],
            // ['filter_id' => 24 , 'property_type_id' => 4 ],
            // ['filter_id' => 27 , 'property_type_id' => 4 ],
            // ['filter_id' => 28 , 'property_type_id' => 4 ],
            // ['filter_id' => 29 , 'property_type_id' => 4 ],
            // ['filter_id' => 30 , 'property_type_id' => 4 ],
            // ['filter_id' => 31 , 'property_type_id' => 4 ],
            // ['filter_id' => 32 , 'property_type_id' => 4 ],
            // ['filter_id' => 33 , 'property_type_id' => 4 ],
            // ['filter_id' => 34 , 'property_type_id' => 4 ],
            // ['filter_id' => 35 , 'property_type_id' => 4 ],
            // ['filter_id' => 36 , 'property_type_id' => 4 ],
            // ['filter_id' => 37 , 'property_type_id' => 4 ],
            // ['filter_id' => 38 , 'property_type_id' => 4 ],

            // ['filter_id' => 39 , 'property_type_id' => 4 ],
            // ['filter_id' => 41 , 'property_type_id' => 4 ],
            // ['filter_id' => 42 , 'property_type_id' => 4 ],
            // ['filter_id' => 43 , 'property_type_id' => 4 ],
            // ['filter_id' => 44 , 'property_type_id' => 4 ],
            // ['filter_id' => 45 , 'property_type_id' => 4 ],

            // ['filter_id' => 46 , 'property_type_id' => 4 ],
            // ['filter_id' => 47 , 'property_type_id' => 4 ],
            // ['filter_id' => 48 , 'property_type_id' => 4 ],
            // ['filter_id' => 49 , 'property_type_id' => 4 ],

            // ['filter_id' => 50 , 'property_type_id' => 4 ],
            // ['filter_id' => 51 , 'property_type_id' => 4 ],
            // ['filter_id' => 52 , 'property_type_id' => 4 ],
            // ['filter_id' => 53 , 'property_type_id' => 4 ],
            // ['filter_id' => 54 , 'property_type_id' => 4 ],
            // ['filter_id' => 55 , 'property_type_id' => 4 ],
            // ['filter_id' => 56 , 'property_type_id' => 4 ],
            // ['filter_id' => 57 , 'property_type_id' => 4 ],
            // ['filter_id' => 58 , 'property_type_id' => 4 ],

            // ['filter_id' => 60 , 'property_type_id' => 4 ],
            // ['filter_id' => 61 , 'property_type_id' => 4 ],
            // ['filter_id' => 62 , 'property_type_id' => 4 ],
            // ['filter_id' => 63 , 'property_type_id' => 4 ],
            // ['filter_id' => 64 , 'property_type_id' => 4 ],
            // ['filter_id' => 65 , 'property_type_id' => 4 ],
            // ['filter_id' => 66 , 'property_type_id' => 4 ],
            // ['filter_id' => 67 , 'property_type_id' => 4 ],
            // ['filter_id' => 68 , 'property_type_id' => 4 ],
            // ['filter_id' => 69 , 'property_type_id' => 4 ],

            // ['filter_id' => 73 , 'property_type_id' => 4 ],
            // ['filter_id' => 74 , 'property_type_id' => 4 ],
            // ['filter_id' => 75 , 'property_type_id' => 4 ],
            // ['filter_id' => 76 , 'property_type_id' => 4 ],
            // ['filter_id' => 77 , 'property_type_id' => 4 ],
            // ['filter_id' => 80 , 'property_type_id' => 4 ],
            // ['filter_id' => 81 , 'property_type_id' => 4 ],
            // ['filter_id' => 82 , 'property_type_id' => 4 ],
            // ['filter_id' => 83 , 'property_type_id' => 4 ],
            // ['filter_id' => 84 , 'property_type_id' => 4 ],
            // ['filter_id' => 85 , 'property_type_id' => 4 ],
            // ['filter_id' => 86 , 'property_type_id' => 4 ],
            // ['filter_id' => 87 , 'property_type_id' => 4 ],
            // ['filter_id' => 88 , 'property_type_id' => 4 ],
            // ['filter_id' => 89 , 'property_type_id' => 4 ],

            // ['filter_id' => 93 , 'property_type_id' => 4 ],
            // ['filter_id' => 95 , 'property_type_id' => 4 ],
            // ['filter_id' => 96 , 'property_type_id' => 4 ],
            // ['filter_id' => 97 , 'property_type_id' => 4 ],
            // ['filter_id' => 98 , 'property_type_id' => 4 ],
            // ['filter_id' => 99 , 'property_type_id' => 4 ],

            // ['filter_id' => 100 , 'property_type_id' => 4 ],
            // ['filter_id' => 101 , 'property_type_id' => 4 ],
            // ['filter_id' => 102 , 'property_type_id' => 4 ],
            // ['filter_id' => 103 , 'property_type_id' => 4 ],

            // ['filter_id' => 104 , 'property_type_id' => 4 ],
            // ['filter_id' => 105 , 'property_type_id' => 4 ],
            // ['filter_id' => 106 , 'property_type_id' => 4 ],
            // ['filter_id' => 107 , 'property_type_id' => 4 ],
            // ['filter_id' => 108 , 'property_type_id' => 4 ],
            // ['filter_id' => 109 , 'property_type_id' => 4 ],
            // ['filter_id' => 110 , 'property_type_id' => 4 ],
            // ['filter_id' => 111 , 'property_type_id' => 4 ],
            // ['filter_id' => 112 , 'property_type_id' => 4 ],

            // // ['filter_id' => 113 , 'property_type_id' => 4 ],
            // ['filter_id' => 114 , 'property_type_id' => 4 ],
            // ['filter_id' => 115 , 'property_type_id' => 4 ],
            // ['filter_id' => 116 , 'property_type_id' => 4 ],
            // ['filter_id' => 117 , 'property_type_id' => 4 ],
            // ['filter_id' => 118 , 'property_type_id' => 4 ],
            // ['filter_id' => 119 , 'property_type_id' => 4 ],
            // ['filter_id' => 120 , 'property_type_id' => 4 ],
            // ['filter_id' => 121 , 'property_type_id' => 4 ],
            // ['filter_id' => 122 , 'property_type_id' => 4 ],
            // ['filter_id' => 123 , 'property_type_id' => 4 ],

            // ['filter_id' => 125 , 'property_type_id' => 4 ],
            // ['filter_id' => 128 , 'property_type_id' => 4 ],
            // ['filter_id' => 129 , 'property_type_id' => 4 ],
            // ['filter_id' => 130 , 'property_type_id' => 4 ],
            // ['filter_id' => 131 , 'property_type_id' => 4 ],
            // ['filter_id' => 132 , 'property_type_id' => 4 ],
            // ['filter_id' => 134 , 'property_type_id' => 4 ],
            // ['filter_id' => 135 , 'property_type_id' => 4 ],
            // ['filter_id' => 137 , 'property_type_id' => 4 ],
            // ['filter_id' => 138 , 'property_type_id' => 4 ],
            // ['filter_id' => 139 , 'property_type_id' => 4 ],
            // ['filter_id' => 141 , 'property_type_id' => 4 ],
            // // ['filter_id' => 142 , 'property_type_id' => 4 ],
            // ['filter_id' => 144 , 'property_type_id' => 4 ],
            // ['filter_id' => 145 , 'property_type_id' => 4 ],
            // ['filter_id' => 146 , 'property_type_id' => 4 ],
          

            // ['filter_id' => 151 , 'property_type_id' => 4 ],
            // ['filter_id' => 153 , 'property_type_id' => 4 ],
            // ['filter_id' => 154 , 'property_type_id' => 4 ],

            // //
            // ['filter_id' => 157 , 'property_type_id' => 1 ],
            // ['filter_id' => 157 , 'property_type_id' => 2 ],
            // ['filter_id' => 157 , 'property_type_id' => 4 ],


            //
            ['filter_id' => 158 , 'property_type_id' => 1 ],
            ['filter_id' => 158 , 'property_type_id' => 2 ],
            ['filter_id' => 158 , 'property_type_id' => 3 ],
            ['filter_id' => 158 , 'property_type_id' => 4 ],

         
           
        ];
    
        foreach ($items as $item) {
            FilterPropertyType::create($item);
        }
    }
}
