<?php

use Illuminate\Database\Seeder;
use App\FilterPropertyType;

class FilterPropertyTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [            
            ['filter_id' => 1  , 'property_type_id' => 1 ],
            ['filter_id' => 2  , 'property_type_id' => 1 ],
            ['filter_id' => 3  , 'property_type_id' => 1 ],
            ['filter_id' => 4  , 'property_type_id' => 1 ],
            ['filter_id' => 5  , 'property_type_id' => 1 ],
            ['filter_id' => 6  , 'property_type_id' => 1 ],
            ['filter_id' => 7  , 'property_type_id' => 1 ],
            ['filter_id' => 8  , 'property_type_id' => 1 ],
            ['filter_id' => 9  , 'property_type_id' => 1 ],
            ['filter_id' => 10 , 'property_type_id' => 1 ],
            ['filter_id' => 11 , 'property_type_id' => 1 ],
            ['filter_id' => 12 , 'property_type_id' => 1 ],
            ['filter_id' => 13 , 'property_type_id' => 1 ],
            ['filter_id' => 14 , 'property_type_id' => 1 ],
            ['filter_id' => 15 , 'property_type_id' => 1 ],
            ['filter_id' => 16 , 'property_type_id' => 1 ],
            ['filter_id' => 17 , 'property_type_id' => 1 ],
            ['filter_id' => 18 , 'property_type_id' => 1 ],
            ['filter_id' => 19 , 'property_type_id' => 1 ],
            ['filter_id' => 20 , 'property_type_id' => 1 ],
            ['filter_id' => 21 , 'property_type_id' => 1 ],
            ['filter_id' => 22 , 'property_type_id' => 1 ],
            ['filter_id' => 23 , 'property_type_id' => 1 ],
            ['filter_id' => 24 , 'property_type_id' => 1 ],
            ['filter_id' => 25 , 'property_type_id' => 1 ],
            ['filter_id' => 26 , 'property_type_id' => 1 ],
            ['filter_id' => 27 , 'property_type_id' => 1 ],
            ['filter_id' => 28 , 'property_type_id' => 1 ],
            ['filter_id' => 29 , 'property_type_id' => 1 ],
            ['filter_id' => 30 , 'property_type_id' => 1 ],
            ['filter_id' => 31 , 'property_type_id' => 1 ],
            ['filter_id' => 32 , 'property_type_id' => 1 ],
            ['filter_id' => 33 , 'property_type_id' => 1 ],
            ['filter_id' => 34 , 'property_type_id' => 1 ],
            ['filter_id' => 35 , 'property_type_id' => 1 ],
            ['filter_id' => 36 , 'property_type_id' => 1 ],
            ['filter_id' => 37 , 'property_type_id' => 1 ],
            ['filter_id' => 38 , 'property_type_id' => 1 ],
            ['filter_id' => 39 , 'property_type_id' => 1 ],
            ['filter_id' => 40 , 'property_type_id' => 1 ],
            ['filter_id' => 41 , 'property_type_id' => 1 ],
            ['filter_id' => 42 , 'property_type_id' => 1 ],
            ['filter_id' => 43 , 'property_type_id' => 1 ],
            ['filter_id' => 44 , 'property_type_id' => 1 ],
            ['filter_id' => 45 , 'property_type_id' => 1 ],
            ['filter_id' => 46 , 'property_type_id' => 1 ],
            ['filter_id' => 47 , 'property_type_id' => 1 ],
            ['filter_id' => 48 , 'property_type_id' => 1 ],
            ['filter_id' => 49 , 'property_type_id' => 1 ],
            ['filter_id' => 1  , 'property_type_id' => 2 ],
            ['filter_id' => 2  , 'property_type_id' => 2 ],
            ['filter_id' => 3  , 'property_type_id' => 2 ],
            ['filter_id' => 5  , 'property_type_id' => 2 ],
            ['filter_id' => 6  , 'property_type_id' => 2 ],
            ['filter_id' => 7  , 'property_type_id' => 2 ],
            ['filter_id' => 8  , 'property_type_id' => 2 ],
            ['filter_id' => 9  , 'property_type_id' => 2 ],
            ['filter_id' => 10 , 'property_type_id' => 2 ],
            ['filter_id' => 11 , 'property_type_id' => 2 ],
            ['filter_id' => 12 , 'property_type_id' => 2 ],
            ['filter_id' => 13 , 'property_type_id' => 2 ],
            ['filter_id' => 14 , 'property_type_id' => 2 ],
            ['filter_id' => 15 , 'property_type_id' => 2 ],
            ['filter_id' => 16 , 'property_type_id' => 2 ],
            ['filter_id' => 17 , 'property_type_id' => 2 ],
            ['filter_id' => 18 , 'property_type_id' => 2 ],
            ['filter_id' => 19 , 'property_type_id' => 2 ],
            ['filter_id' => 20 , 'property_type_id' => 2 ],
            ['filter_id' => 21 , 'property_type_id' => 2 ],
            ['filter_id' => 22 , 'property_type_id' => 2 ],
            ['filter_id' => 23 , 'property_type_id' => 2 ],
            ['filter_id' => 24 , 'property_type_id' => 2 ],
            ['filter_id' => 25 , 'property_type_id' => 2 ],
            ['filter_id' => 26 , 'property_type_id' => 2 ],
            ['filter_id' => 27 , 'property_type_id' => 2 ],
            ['filter_id' => 28 , 'property_type_id' => 2 ],
            ['filter_id' => 29 , 'property_type_id' => 2 ],
            ['filter_id' => 30 , 'property_type_id' => 2 ],
            ['filter_id' => 31 , 'property_type_id' => 2 ],
            ['filter_id' => 32 , 'property_type_id' => 2 ],
            ['filter_id' => 33 , 'property_type_id' => 2 ],
            ['filter_id' => 34 , 'property_type_id' => 2 ],
            ['filter_id' => 35 , 'property_type_id' => 2 ],
            ['filter_id' => 36 , 'property_type_id' => 2 ],
            ['filter_id' => 37 , 'property_type_id' => 2 ],
            ['filter_id' => 38 , 'property_type_id' => 2 ],
            ['filter_id' => 39 , 'property_type_id' => 2 ],
            ['filter_id' => 40 , 'property_type_id' => 2 ],
            ['filter_id' => 41 , 'property_type_id' => 2 ],
            ['filter_id' => 42 , 'property_type_id' => 2 ],
            ['filter_id' => 43 , 'property_type_id' => 2 ],
            ['filter_id' => 44 , 'property_type_id' => 2 ],
            ['filter_id' => 45 , 'property_type_id' => 2 ],
            ['filter_id' => 46 , 'property_type_id' => 2 ],
            ['filter_id' => 47 , 'property_type_id' => 2 ],
            ['filter_id' => 48 , 'property_type_id' => 2 ],
            ['filter_id' => 49 , 'property_type_id' => 2 ],
            ['filter_id' => 2  , 'property_type_id' => 3 ],
            ['filter_id' => 14 , 'property_type_id' => 3 ],
            ['filter_id' => 15 , 'property_type_id' => 3 ],
            ['filter_id' => 24 , 'property_type_id' => 3 ],
            ['filter_id' => 44 , 'property_type_id' => 3 ],
            ['filter_id' => 46 , 'property_type_id' => 3 ],
            ['filter_id' => 49 , 'property_type_id' => 3 ],
            ['filter_id' => 1  , 'property_type_id' => 4 ],
            ['filter_id' => 2  , 'property_type_id' => 4 ],
            ['filter_id' => 3  , 'property_type_id' => 4 ],
            ['filter_id' => 5  , 'property_type_id' => 4 ],
            ['filter_id' => 6  , 'property_type_id' => 4 ],
            ['filter_id' => 7  , 'property_type_id' => 4 ],
            ['filter_id' => 8  , 'property_type_id' => 4 ],
            ['filter_id' => 9  , 'property_type_id' => 4 ],
            ['filter_id' => 10 , 'property_type_id' => 4 ],
            ['filter_id' => 11 , 'property_type_id' => 4 ],
            ['filter_id' => 12 , 'property_type_id' => 4 ],
            ['filter_id' => 13 , 'property_type_id' => 4 ],
            ['filter_id' => 16 , 'property_type_id' => 4 ],
            ['filter_id' => 17 , 'property_type_id' => 4 ],
            ['filter_id' => 21 , 'property_type_id' => 4 ],
            ['filter_id' => 22 , 'property_type_id' => 4 ],
            ['filter_id' => 23 , 'property_type_id' => 4 ],
            ['filter_id' => 24 , 'property_type_id' => 4 ],
            ['filter_id' => 32 , 'property_type_id' => 4 ],
            ['filter_id' => 33 , 'property_type_id' => 4 ],
            ['filter_id' => 34 , 'property_type_id' => 4 ],
            ['filter_id' => 38 , 'property_type_id' => 4 ],
            ['filter_id' => 42 , 'property_type_id' => 4 ],
            ['filter_id' => 43 , 'property_type_id' => 4 ],
            ['filter_id' => 46 , 'property_type_id' => 4 ],
           
        ];
    
        foreach ($items as $item) {
            FilterPropertyType::create($item);
        }
    }
}
